#ifndef __GALOIS_IR_MAIN_H__
#define __GALOIS_IR_MAIN_H__

#include <linux/input.h>
#include "ir_key_def.h"

typedef struct ir_keymap {
	MV_IR_KEY_CODE_t ir_key;
	uint input_key;
}ir_keymap_t;

ir_keymap_t keymap_tab[] = {
	{MV_IR_KEY_NULL, 		KEY_RESERVED}, 	/* no key */
	
	{MV_IR_KEY_POWER,		KEY_POWER},
	{MV_IR_KEY_OPENCLOSE,		KEY_OPEN},

	/* digital keys */
	{MV_IR_KEY_DIGIT_1,		KEY_1},
	{MV_IR_KEY_DIGIT_2,		KEY_2},
	{MV_IR_KEY_DIGIT_3,		KEY_3},
	{MV_IR_KEY_DIGIT_4,		KEY_4},
	{MV_IR_KEY_DIGIT_5,		KEY_5},
	{MV_IR_KEY_DIGIT_6,		KEY_6},
	{MV_IR_KEY_DIGIT_7,		KEY_7},
	{MV_IR_KEY_DIGIT_8,		KEY_8},
	{MV_IR_KEY_DIGIT_9,		KEY_9},
	{MV_IR_KEY_DIGIT_0,		KEY_0},

	/* for BD */
	{MV_IR_KEY_INFO,		KEY_INFO},
	{MV_IR_KEY_SETUPMENU,		KEY_HOME},
	{MV_IR_KEY_CANCEL, 		KEY_CANCEL},	/* no key */

	{MV_IR_KEY_DISCMENU,		KEY_CONTEXT_MENU},
	{MV_IR_KEY_TITLEMENU,		KEY_TITLE},
	{MV_IR_KEY_SUBTITLE,		KEY_SUBTITLE},
	{MV_IR_KEY_ANGLE,		KEY_ANGLE},
	{MV_IR_KEY_AUDIO,		KEY_AUDIO},
	{MV_IR_KEY_SEARCH,		KEY_SEARCH},
	{MV_IR_KEY_ZOOM,		KEY_ZOOM},
	{MV_IR_KEY_DISPLAY,		KEY_SCREEN},

	{MV_IR_KEY_REPEAT,		KEY_MEDIA_REPEAT},
	{MV_IR_KEY_REPEAT_AB,		KEY_AB},
	{MV_IR_KEY_MARKER,		KEY_MARKER},
	{MV_IR_KEY_EXIT,		KEY_EXIT},
	{MV_IR_KEY_A,			KEY_RED},
	{MV_IR_KEY_B,			KEY_GREEN},
	{MV_IR_KEY_C,			KEY_YELLOW},
	{MV_IR_KEY_D,			KEY_BLUE},

	/* IR misc around ENTER */
	{MV_IR_KEY_CLEAR,		KEY_CLEAR},
	{MV_IR_KEY_VIDEO_FORMAT,	KEY_VIDEO},
	{MV_IR_KEY_STEP,		KEY_STEP},
	{MV_IR_KEY_RETURN,		KEY_ESC},

	/* up down left right enter */
	{MV_IR_KEY_UP,			KEY_UP},
	{MV_IR_KEY_DOWN,		KEY_DOWN},
	{MV_IR_KEY_LEFT,		KEY_LEFT},
	{MV_IR_KEY_RIGHT,		KEY_RIGHT},
	{MV_IR_KEY_ENTER,		KEY_ENTER},

	/* for BD */
	{MV_IR_KEY_SLOW,		KEY_SLOW},
	{MV_IR_KEY_PAUSE,		KEY_PAUSE},
	{MV_IR_KEY_PLAY,		KEY_PLAY},
	{MV_IR_KEY_STOP,		KEY_STOP},
	{MV_IR_KEY_PLAY_PAUSE, 		KEY_PLAYPAUSE},	/* no key */

	{MV_IR_KEY_SKIP_BACKWARD,	KEY_PREVIOUS},
	{MV_IR_KEY_SKIP_FORWARD,	KEY_NEXT},
	{MV_IR_KEY_SLOW_BACKWARD, 	KEY_RESERVED},	/* no key */
	{MV_IR_KEY_SLOW_FORWARD,  	KEY_RESERVED},	/* no key */
	{MV_IR_KEY_FAST_BACKWARD,	KEY_REWIND},
	{MV_IR_KEY_FAST_FORWARD,	KEY_FORWARD},

	/* bottom keys */
	{MV_IR_KEY_F1,			KEY_F1},
	{MV_IR_KEY_F2,			KEY_F2},
	{MV_IR_KEY_F3,			KEY_F3},
	{MV_IR_KEY_F4,			KEY_F4},
	{MV_IR_KEY_F5,			KEY_F5},
	{MV_IR_KEY_F6,			KEY_F6},
	{MV_IR_KEY_F7,			KEY_F7},
	{MV_IR_KEY_F8,			KEY_F8},

	/* for future */
	{MV_IR_KEY_VOL_PLUS, 		KEY_VOLUMEUP},		/* no key */
	{MV_IR_KEY_VOL_MINUS, 		KEY_VOLUMEDOWN},	/* no key */
	{MV_IR_KEY_VOL_MUTE, 		KEY_MUTE},			/* no key */
	{MV_IR_KEY_CHANNEL_PLUS, 	KEY_CHANNELUP},		/* no key */
	{MV_IR_KEY_CHANNEL_MINUS, 	KEY_CHANNELDOWN},	/* no key */

	/* obsoleted keys */
	{MV_IR_KEY_MENU,		KEY_MENU},
	{MV_IR_KEY_INPUTSEL,		KEY_RESERVED},
	{MV_IR_KEY_ANYNET,		KEY_RESERVED},
	{MV_IR_KEY_TELEVISION,		KEY_TV},
	{MV_IR_KEY_CHANNEL_LIST,	KEY_RESERVED},
	{MV_IR_KEY_TVPOWER,		KEY_RESERVED},
};
#endif
