obj-$(CONFIG_MV88DE3010_DIRECTFB_FUSION) += fusion.o

fusion-objs := linux/drivers/char/fusion/call.o linux/drivers/char/fusion/entries.o linux/drivers/char/fusion/fifo.o linux/drivers/char/fusion/fusiondev.o linux/drivers/char/fusion/fusionee.o linux/drivers/char/fusion/list.o linux/drivers/char/fusion/property.o linux/drivers/char/fusion/reactor.o linux/drivers/char/fusion/ref.o linux/drivers/char/fusion/skirmish.o linux/drivers/char/fusion/shmpool.o

