#ifndef __GALOIS_HAL_COM_H__
#define __GALOIS_HAL_COM_H__


#define INT_UNMASK_BIT		0
#define INT_MASK_BIT		1
#define INT_ENABLE_BIT		1
#define INT_DISABLE_BIT		0
#define INT_UNMASK_ALL		0x00000000
#define INT_MASK_ALL		0xFFFFFFFF
#define INT_ENABLE_ALL		0xFFFFFFFF	
#define INT_DISABLE_ALL		0x00000000

#define INT_ACTIVE_HIGH		1
#define INT_ACTIVE_LOW		0
#define INT_EDGE_TRIG		1
#define INT_LEVEL_TRIG		0

#define APB_ICTL_REG_L		0
#define APB_ICTL_REG_H		1

#endif // __GALOIS_HAL_COM_H__

